export const ERROR_CODE = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_INACTIVE: "USER_INACTIVE",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  FEATURE_DISABLED: "FEATURE_DISABLED",
  CONFIGURATION_ERROR: "CONFIGURATION_ERROR",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  TWO_FACTOR_REQUIRED: "TWO_FACTOR_REQUIRED",
  TWO_FACTOR_INVALID_CODE: "TWO_FACTOR_INVALID_CODE",
  TWO_FACTOR_ALREADY_ENABLED: "TWO_FACTOR_ALREADY_ENABLED",
  GOOGLE_AUTH_FAILED: "GOOGLE_AUTH_FAILED",
} as const;

export type ErrorCode = keyof typeof ERROR_CODE;
