export const ERROR_CODE = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_INACTIVE: "USER_INACTIVE",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  CRAWL_JOB_NOT_FOUND: "CRAWL_JOB_NOT_FOUND",
  CRAWL_JOB_ALREADY_COMPLETED: "CRAWL_JOB_ALREADY_COMPLETED",
  PRIVATE_IP_BLOCKED: "PRIVATE_IP_BLOCKED",
  INVALID_URL: "INVALID_URL",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  TOKEN_USED: "TOKEN_USED",
  APPLICATION_NOT_FOUND: "APPLICATION_NOT_FOUND",
} as const;

export type ErrorCode = keyof typeof ERROR_CODE;
