export const ACTIVITY_ACTIONS = {
  // Auth
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",

  // User
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",

  // Task
  CREATE_TASK: "CREATE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",

  // Task Assignment
  ASSIGN_TASK: "ASSIGN_TASK",
  UPDATE_ASSIGNMENT: "UPDATE_ASSIGNMENT",
  DELETE_ASSIGNMENT: "DELETE_ASSIGNMENT",

  // Task Submission
  CREATE_SUBMISSION: "CREATE_SUBMISSION",
  UPDATE_SUBMISSION: "UPDATE_SUBMISSION",
  REVIEW_SUBMISSION: "REVIEW_SUBMISSION",
  DELETE_SUBMISSION: "DELETE_SUBMISSION",

  // Weekly Evaluation
  CREATE_EVALUATION: "CREATE_EVALUATION",
  UPDATE_EVALUATION: "UPDATE_EVALUATION",
  DELETE_EVALUATION: "DELETE_EVALUATION",

  // Daily Report
  CREATE_DAILY_REPORT: "CREATE_DAILY_REPORT",
} as const;

export type ActivityAction = keyof typeof ACTIVITY_ACTIONS;
