export const ACTIVITY_ACTIONS = {
  // Auth
  LOGIN: "LOGIN",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  RESET_PASSWORD: "RESET_PASSWORD",
  CHANGE_PASSWORD: "CHANGE_PASSWORD",

  // User
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  // Department & Position
  CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  CREATE_POSITION: "CREATE_POSITION",
  UPDATE_POSITION: "UPDATE_POSITION",
  DELETE_POSITION: "DELETE_POSITION",

  // Task
  CREATE_TASK: "CREATE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  BULK_IMPORT_TASKS: "BULK_IMPORT_TASKS",

  // Task Assignment
  ASSIGN_TASK: "ASSIGN_TASK",
  UPDATE_ASSIGNMENT: "UPDATE_ASSIGNMENT",
  DELETE_ASSIGNMENT: "DELETE_ASSIGNMENT",

  // Task Submission
  CREATE_SUBMISSION: "CREATE_SUBMISSION",
  UPDATE_SUBMISSION: "UPDATE_SUBMISSION",
  REVIEW_SUBMISSION: "REVIEW_SUBMISSION",
  DELETE_SUBMISSION: "DELETE_SUBMISSION",

  // Weekly Evaluation
  CREATE_EVALUATION: "CREATE_EVALUATION",
  UPDATE_EVALUATION: "UPDATE_EVALUATION",
  DELETE_EVALUATION: "DELETE_EVALUATION",

  // Daily Report
  CREATE_DAILY_REPORT: "CREATE_DAILY_REPORT",

  // Application Invite & Submit
  CREATE_APPLICATION_INVITE: "CREATE_APPLICATION_INVITE",
  REVOKE_APPLICATION_INVITE: "REVOKE_APPLICATION_INVITE",
  SUBMIT_APPLICATION: "SUBMIT_APPLICATION",

  // Regulations
  CREATE_REGULATION: "CREATE_REGULATION",
  UPDATE_REGULATION: "UPDATE_REGULATION",
  DELETE_REGULATION: "DELETE_REGULATION",
  ACTIVATE_REGULATION: "ACTIVATE_REGULATION",

  // Meeting
  CREATE_MEETING: "CREATE_MEETING",
  UPDATE_MEETING: "UPDATE_MEETING",
  CANCEL_MEETING: "CANCEL_MEETING",
  DELETE_MEETING: "DELETE_MEETING",
  JOIN_MEETING: "JOIN_MEETING",
  INVITE_MEETING_PARTICIPANT: "INVITE_MEETING_PARTICIPANT",
  RSVP_MEETING: "RSVP_MEETING",
  SUBMIT_ABSENCE: "SUBMIT_ABSENCE",
  REVIEW_ABSENCE: "REVIEW_ABSENCE",
} as const;

export type ActivityAction = keyof typeof ACTIVITY_ACTIONS;
