export const AUDIT_ACTION = {
  CREATE_ROLE: "CREATE_ROLE",
  UPDATE_ROLE: "UPDATE_ROLE",
  DELETE_ROLE: "DELETE_ROLE",
  SYNC_ROLE_PERMISSIONS: "SYNC_ROLE_PERMISSIONS",
  REMOVE_ROLE_PERMISSION: "REMOVE_ROLE_PERMISSION",
  ASSIGN_USER_ROLE: "ASSIGN_USER_ROLE",
  ENABLE_MAINTENANCE: "ENABLE_MAINTENANCE",
  UPDATE_MAINTENANCE: "UPDATE_MAINTENANCE",
  DISABLE_MAINTENANCE: "DISABLE_MAINTENANCE",
  CREATE_NOTIFICATION_TEMPLATE: "CREATE_NOTIFICATION_TEMPLATE",
  UPDATE_NOTIFICATION_TEMPLATE: "UPDATE_NOTIFICATION_TEMPLATE",
  DELETE_NOTIFICATION_TEMPLATE: "DELETE_NOTIFICATION_TEMPLATE",
  CREATE_API_KEY: "CREATE_API_KEY",
  REVOKE_API_KEY: "REVOKE_API_KEY",
  TOGGLE_API_KEY: "TOGGLE_API_KEY",
  CREATE_WEBHOOK: "CREATE_WEBHOOK",
  UPDATE_WEBHOOK: "UPDATE_WEBHOOK",
  DELETE_WEBHOOK: "DELETE_WEBHOOK",
  TRIGGER_WEBHOOK_RETRY: "TRIGGER_WEBHOOK_RETRY",
  CREATE_SYSTEM_CONFIG: "CREATE_SYSTEM_CONFIG",
  UPDATE_SYSTEM_CONFIG: "UPDATE_SYSTEM_CONFIG",
  DELETE_SYSTEM_CONFIG: "DELETE_SYSTEM_CONFIG",
  TOGGLE_FEATURE_FLAG: "TOGGLE_FEATURE_FLAG",
  TRIGGER_CRON_JOB: "TRIGGER_CRON_JOB",
  CLEANUP_AUDIT_LOGS: "CLEANUP_AUDIT_LOGS",
  CLEANUP_UNCONFIRMED_UPLOADS: "CLEANUP_UNCONFIRMED_UPLOADS",
  CLEANUP_EXPIRED_TOKENS: "CLEANUP_EXPIRED_TOKENS",
  SEND_SUMMARY_DIGEST: "SEND_SUMMARY_DIGEST",
  REVOKE_USER_SESSION: "REVOKE_USER_SESSION",
  REVOKE_ALL_USER_SESSIONS: "REVOKE_ALL_USER_SESSIONS",
  DELETE_USER_DEVICE: "DELETE_USER_DEVICE",
  REQUEST_ACCOUNT_DEACTIVATION: "REQUEST_ACCOUNT_DEACTIVATION",
  CONFIRM_ACCOUNT_DEACTIVATION: "CONFIRM_ACCOUNT_DEACTIVATION",
  ENABLE_2FA: "ENABLE_2FA",
  DISABLE_2FA: "DISABLE_2FA",
  VERIFY_2FA_LOGIN: "VERIFY_2FA_LOGIN",
  REGENERATE_2FA_BACKUP_CODES: "REGENERATE_2FA_BACKUP_CODES",
  LOGIN_GOOGLE: "LOGIN_GOOGLE",
  LINK_SOCIAL_ACCOUNT: "LINK_SOCIAL_ACCOUNT",
  UNLINK_SOCIAL_ACCOUNT: "UNLINK_SOCIAL_ACCOUNT",

  // Departments & Positions
  CREATE_DEPARTMENT: "CREATE_DEPARTMENT",
  UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
  DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  CREATE_POSITION: "CREATE_POSITION",
  UPDATE_POSITION: "UPDATE_POSITION",
  DELETE_POSITION: "DELETE_POSITION",

  // Leaders
  CREATE_LEADER: "CREATE_LEADER",
  UPDATE_LEADER: "UPDATE_LEADER",
  DELETE_LEADER: "DELETE_LEADER",

  // Interns
  CREATE_INTERN: "CREATE_INTERN",
  UPDATE_INTERN: "UPDATE_INTERN",
  DELETE_INTERN: "DELETE_INTERN",
  ASSIGN_LEADER: "ASSIGN_LEADER",
} as const;

export type AuditAction = keyof typeof AUDIT_ACTION;

export const AUDIT_TARGET_TYPE = {
  ROLE: "ROLE",
  USER: "USER",
  PERMISSION: "PERMISSION",
  MAINTENANCE_CONFIG: "MAINTENANCE_CONFIG",
  NOTIFICATION_TEMPLATE: "NOTIFICATION_TEMPLATE",
  API_KEY: "API_KEY",
  WEBHOOK_ENDPOINT: "WEBHOOK_ENDPOINT",
  WEBHOOK_DELIVERY: "WEBHOOK_DELIVERY",
  SYSTEM_CONFIG: "SYSTEM_CONFIG",
  CRON_JOB: "CRON_JOB",
  DEPARTMENT: "DEPARTMENT",
  POSITION: "POSITION",
  LEADER: "LEADER",
  INTERN: "INTERN",
} as const;

export type AuditTargetType = keyof typeof AUDIT_TARGET_TYPE;

export const SYSTEM_TARGET_ID = "SYSTEM";
