export const AUDIT_ACTION = {
  CREATE_ROLE: 'CREATE_ROLE',
  UPDATE_ROLE: 'UPDATE_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
  SYNC_ROLE_PERMISSIONS: 'SYNC_ROLE_PERMISSIONS',
  REMOVE_ROLE_PERMISSION: 'REMOVE_ROLE_PERMISSION',
  ASSIGN_USER_ROLE: 'ASSIGN_USER_ROLE',
  ENABLE_MAINTENANCE: 'ENABLE_MAINTENANCE',
  UPDATE_MAINTENANCE: 'UPDATE_MAINTENANCE',
  DISABLE_MAINTENANCE: 'DISABLE_MAINTENANCE',
  CREATE_NOTIFICATION_TEMPLATE: 'CREATE_NOTIFICATION_TEMPLATE',
  UPDATE_NOTIFICATION_TEMPLATE: 'UPDATE_NOTIFICATION_TEMPLATE',
  DELETE_NOTIFICATION_TEMPLATE: 'DELETE_NOTIFICATION_TEMPLATE',
  CREATE_API_KEY: 'CREATE_API_KEY',
  REVOKE_API_KEY: 'REVOKE_API_KEY',
  CREATE_WEBHOOK: 'CREATE_WEBHOOK',
  UPDATE_WEBHOOK: 'UPDATE_WEBHOOK',
  DELETE_WEBHOOK: 'DELETE_WEBHOOK',
  TRIGGER_WEBHOOK_RETRY: 'TRIGGER_WEBHOOK_RETRY',
  CREATE_SYSTEM_CONFIG: 'CREATE_SYSTEM_CONFIG',
  UPDATE_SYSTEM_CONFIG: 'UPDATE_SYSTEM_CONFIG',
  DELETE_SYSTEM_CONFIG: 'DELETE_SYSTEM_CONFIG',
  TOGGLE_FEATURE_FLAG: 'TOGGLE_FEATURE_FLAG',
} as const;

export type AuditAction = keyof typeof AUDIT_ACTION;

export const AUDIT_TARGET_TYPE = {
  ROLE: 'ROLE',
  USER: 'USER',
  PERMISSION: 'PERMISSION',
  MAINTENANCE_CONFIG: 'MAINTENANCE_CONFIG',
  NOTIFICATION_TEMPLATE: 'NOTIFICATION_TEMPLATE',
  API_KEY: 'API_KEY',
  WEBHOOK_ENDPOINT: 'WEBHOOK_ENDPOINT',
  WEBHOOK_DELIVERY: 'WEBHOOK_DELIVERY',
  SYSTEM_CONFIG: 'SYSTEM_CONFIG',
} as const;

export type AuditTargetType = keyof typeof AUDIT_TARGET_TYPE;

export const SYSTEM_TARGET_ID = 'SYSTEM';

