export const NOTIFICATION_EVENT = {
  NEW: "NOTIFICATION_NEW",
  DELETED: "NOTIFICATION_DELETED",
  READ_ALL: "NOTIFICATION_READ_ALL",
  CLEARED_READ: "NOTIFICATION_CLEARED_READ",
} as const;

export type NotificationEventType = typeof NOTIFICATION_EVENT[keyof typeof NOTIFICATION_EVENT];
