export const PERMISSIONS = {
  // User Management
  USER_READ: "USER_READ",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  USER_ROLE_ASSIGN: "USER_ROLE_ASSIGN",

  // Role & Permission Management
  ROLE_READ: "ROLE_READ",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_UPDATE: "ROLE_UPDATE",
  ROLE_DELETE: "ROLE_DELETE",
  PERMISSION_READ: "PERMISSION_READ",
  ROLE_PERMISSION_ASSIGN: "ROLE_PERMISSION_ASSIGN",

  // Notifications & Emails
  NOTIFICATION_READ: "NOTIFICATION_READ",
  NOTIFICATION_CREATE: "NOTIFICATION_CREATE",
  NOTIFICATION_UPDATE: "NOTIFICATION_UPDATE",
  NOTIFICATION_DELETE: "NOTIFICATION_DELETE",
  NOTIFICATION_TEMPLATE_READ: "NOTIFICATION_TEMPLATE_READ",
  NOTIFICATION_TEMPLATE_MANAGE: "NOTIFICATION_TEMPLATE_MANAGE",
  TEMPLATE_MANAGE: "NOTIFICATION_TEMPLATE_MANAGE",
  NOTIFICATION_SETTING_READ: "NOTIFICATION_SETTING_READ",
  NOTIFICATION_SETTING_UPDATE: "NOTIFICATION_SETTING_UPDATE",

  // Audit Logs
  AUDIT_LOG_READ: "AUDIT_LOG_READ",
  AUDIT_LOG_VIEW: "AUDIT_LOG_READ",

  // System Maintenance
  MAINTENANCE_READ: "MAINTENANCE_READ",
  MAINTENANCE_MANAGE: "MAINTENANCE_MANAGE",
  MAINTENANCE_BYPASS: "MAINTENANCE_BYPASS",

  // API Keys & Integrations
  API_KEY_READ: "API_KEY_READ",
  API_KEY_MANAGE: "API_KEY_MANAGE",

  // Webhooks
  WEBHOOK_READ: "WEBHOOK_READ",
  WEBHOOK_MANAGE: "WEBHOOK_MANAGE",

  // System Configuration & Feature Flags
  SYSTEM_CONFIG_READ: "SYSTEM_CONFIG_READ",
  SYSTEM_CONFIG_MANAGE: "SYSTEM_CONFIG_MANAGE",

  // Scheduled / Cron Jobs Management
  CRON_JOB_READ: "CRON_JOB_READ",
  CRON_JOB_MANAGE: "CRON_JOB_MANAGE",

  // Departments & Positions
  DEPARTMENT_READ: "DEPARTMENT_READ",
  DEPARTMENT_CREATE: "DEPARTMENT_CREATE",
  DEPARTMENT_UPDATE: "DEPARTMENT_UPDATE",
  DEPARTMENT_DELETE: "DEPARTMENT_DELETE",
  POSITION_READ: "POSITION_READ",
  POSITION_CREATE: "POSITION_CREATE",
  POSITION_UPDATE: "POSITION_UPDATE",
  POSITION_DELETE: "POSITION_DELETE",

  // Leaders
  LEADER_READ: "LEADER_READ",
  LEADER_CREATE: "LEADER_CREATE",
  LEADER_UPDATE: "LEADER_UPDATE",
  LEADER_DELETE: "LEADER_DELETE",

  // Interns
  INTERN_READ: "INTERN_READ",
  INTERN_CREATE: "INTERN_CREATE",
  INTERN_UPDATE: "INTERN_UPDATE",
  INTERN_DELETE: "INTERN_DELETE",
  INTERN_ASSIGN_LEADER: "INTERN_ASSIGN_LEADER",

  // Recruitment & Applications
  APPLICATION_READ: "APPLICATION_READ",
  APPLICATION_CREATE: "APPLICATION_CREATE",
  APPLICATION_ASSIGN: "APPLICATION_ASSIGN",
  APPLICATION_REVIEW: "APPLICATION_REVIEW",
  APPLICATION_DELETE: "APPLICATION_DELETE",
  APPLICATION_INVITE_READ: "APPLICATION_INVITE_READ",
  APPLICATION_INVITE_CREATE: "APPLICATION_INVITE_CREATE",
  APPLICATION_INVITE_REVOKE: "APPLICATION_INVITE_REVOKE",

  // Task Groups
  TASK_GROUP_READ: "TASK_GROUP_READ",
  TASK_GROUP_CREATE: "TASK_GROUP_CREATE",
  TASK_GROUP_UPDATE: "TASK_GROUP_UPDATE",
  TASK_GROUP_DELETE: "TASK_GROUP_DELETE",

  // Tasks & Attachments
  TASK_READ: "TASK_READ",
  TASK_CREATE: "TASK_CREATE",
  TASK_UPDATE: "TASK_UPDATE",
  TASK_DELETE: "TASK_DELETE",
  TASK_ATTACHMENT_UPLOAD: "TASK_ATTACHMENT_UPLOAD",
  TASK_ATTACHMENT_DELETE: "TASK_ATTACHMENT_DELETE",

  // Task Assignments
  TASK_ASSIGNMENT_READ: "TASK_ASSIGNMENT_READ",
  TASK_ASSIGNMENT_CREATE: "TASK_ASSIGNMENT_CREATE",
  TASK_ASSIGNMENT_UPDATE: "TASK_ASSIGNMENT_UPDATE",
  TASK_ASSIGNMENT_DELETE: "TASK_ASSIGNMENT_DELETE",
  TASK_ASSIGNMENT_APPROVE: "TASK_ASSIGNMENT_APPROVE",

  // Task Submissions
  TASK_SUBMISSION_READ: "TASK_SUBMISSION_READ",
  TASK_SUBMISSION_CREATE: "TASK_SUBMISSION_CREATE",
  TASK_SUBMISSION_UPDATE: "TASK_SUBMISSION_UPDATE",
  TASK_SUBMISSION_DELETE: "TASK_SUBMISSION_DELETE",
  TASK_SUBMISSION_REVIEW: "TASK_SUBMISSION_REVIEW",

  // Meetings
  MEETING_READ: "MEETING_READ",
  MEETING_CREATE: "MEETING_CREATE",
  MEETING_UPDATE: "MEETING_UPDATE",
  MEETING_DELETE: "MEETING_DELETE",
  MEETING_ATTEND: "MEETING_ATTEND",
  MEETING_ABSENCE_SUBMIT: "MEETING_ABSENCE_SUBMIT",
  MEETING_ABSENCE_REVIEW: "MEETING_ABSENCE_REVIEW",

  // Absences
  ABSENCE_READ: "ABSENCE_READ",
  ABSENCE_CREATE: "ABSENCE_CREATE",
  ABSENCE_REVIEW: "ABSENCE_REVIEW",

  // Daily Reports
  DAILY_REPORT_READ: "DAILY_REPORT_READ",
  DAILY_REPORT_CREATE: "DAILY_REPORT_CREATE",
  DAILY_REPORT_UPDATE: "DAILY_REPORT_UPDATE",
  DAILY_REPORT_DELETE: "DAILY_REPORT_DELETE",
  DAILY_REPORT_FEEDBACK: "DAILY_REPORT_FEEDBACK",

  // Weekly Evaluations
  WEEKLY_EVALUATION_READ: "WEEKLY_EVALUATION_READ",
  WEEKLY_EVALUATION_CREATE: "WEEKLY_EVALUATION_CREATE",
  WEEKLY_EVALUATION_UPDATE: "WEEKLY_EVALUATION_UPDATE",
  WEEKLY_EVALUATION_DELETE: "WEEKLY_EVALUATION_DELETE",
  WEEKLY_EVALUATION_CONFIRM: "WEEKLY_EVALUATION_CONFIRM",
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;

export const PERMISSION_PUBSUB_CHANNEL = "permission:events";

export const PERMISSION_PUBSUB_ACTION = {
  INVALIDATE_ROLE: "INVALIDATE_ROLE",
  INVALIDATE_USER: "INVALIDATE_USER",
  CLEAR: "CLEAR",
} as const;

