export const PERMISSIONS = {
  // User Management
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_ROLE_ASSIGN: 'USER_ROLE_ASSIGN',

  // Role & Permission Management
  ROLE_READ: 'ROLE_READ',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  PERMISSION_READ: 'PERMISSION_READ',
  ROLE_PERMISSION_ASSIGN: 'ROLE_PERMISSION_ASSIGN',

  // Notifications & Emails
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATION_CREATE: 'NOTIFICATION_CREATE',
  NOTIFICATION_UPDATE: 'NOTIFICATION_UPDATE',
  NOTIFICATION_DELETE: 'NOTIFICATION_DELETE',
  NOTIFICATION_TEMPLATE_READ: 'NOTIFICATION_TEMPLATE_READ',
  NOTIFICATION_TEMPLATE_MANAGE: 'NOTIFICATION_TEMPLATE_MANAGE',

  // Audit Logs
  AUDIT_LOG_READ: 'AUDIT_LOG_READ',

  // System Maintenance
  MAINTENANCE_READ: 'MAINTENANCE_READ',
  MAINTENANCE_MANAGE: 'MAINTENANCE_MANAGE',
  MAINTENANCE_BYPASS: 'MAINTENANCE_BYPASS',

  // API Keys & Integrations
  API_KEY_READ: 'API_KEY_READ',
  API_KEY_MANAGE: 'API_KEY_MANAGE',

  // Webhooks
  WEBHOOK_READ: 'WEBHOOK_READ',
  WEBHOOK_MANAGE: 'WEBHOOK_MANAGE',

  // System Configuration & Feature Flags
  SYSTEM_CONFIG_READ: 'SYSTEM_CONFIG_READ',
  SYSTEM_CONFIG_MANAGE: 'SYSTEM_CONFIG_MANAGE',

  // Scheduled / Cron Jobs Management
  CRON_JOB_READ: 'CRON_JOB_READ',
  CRON_JOB_MANAGE: 'CRON_JOB_MANAGE',
} as const;


export type PermissionKey = keyof typeof PERMISSIONS;

