export const PERMISSIONS = {
  // User Management
  USER_READ: 'USER_READ',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  USER_ROLE_ASSIGN: 'USER_ROLE_ASSIGN',

  // Role & Permission Management
  ROLE_READ: 'ROLE_READ',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
  PERMISSION_READ: 'PERMISSION_READ',
  ROLE_PERMISSION_ASSIGN: 'ROLE_PERMISSION_ASSIGN',

  // Notifications & Emails
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATION_CREATE: 'NOTIFICATION_CREATE',
  NOTIFICATION_UPDATE: 'NOTIFICATION_UPDATE',
  NOTIFICATION_DELETE: 'NOTIFICATION_DELETE',

  // Audit Logs
  AUDIT_LOG_READ: 'AUDIT_LOG_READ',
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
